spring.application.name=estimate-management-api

# MySQL connection
spring.datasource.url=jdbc:mysql://${ESTIMATE_DB_HOST:ldb-xium-ap1.mysql-v2.dev.local}:3306/estimate_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Tokyo
spring.datasource.username=${ESTIMATE_DB_USER:user-name}
spring.datasource.password=${ESTIMATE_DB_PW:password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Spring Data JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
